name: gogg
version: '0.1.0'
summary: Gogg downloader
description: |
  Gogg is a minimalistic command-line tool for downloading game files from GOG.com.
  It is written in Go and uses the official GOG API to download game files.

  Gogg can be used to fully automate the download process with a few simple commands.
  For more information, please see Gogg's documentation on GitHub (https://github.com/habedi/gogg/docs/README.md).

base: core24
confinement: strict
grade: devel
compression: lzo
assumes:
  - snapd2.54  # Minimum version of Snapd required

license: MIT
website: https://github.com/habedi/gogg
contact: https://github.com/habedi
source-code: https://github.com/habedi/gogg
issues: [ https://github.com/habedi/gogg/issues ]

parts:
  gogg:
    plugin: make
    source: .
    build-attributes: [ no-system-libraries ]
    build-packages:
      - make
      - gcc
      - golang
    override-build: |
      make build
      cp LICENSE $SNAPCRAFT_PART_INSTALL/LICENSE
      cp bin/gogg $SNAPCRAFT_PART_INSTALL/gogg
    stage:
      - gogg
      - LICENSE

apps:
  gogg:
    command: gogg
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - browser-support
      - desktop
      - desktop-legacy
      - x11
      - wayland
