name: Build Gogg

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          lfs: true

      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            make
            mingw-w64-x86_64-go
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-freeglut

      - name: Build Gogg
        shell: msys2 {0}
        run: |
          make release GOGG_BINARY=gogg.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.sha }}
          path: bin/gogg.exe
